Registration_løsning/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Registration_løsning.Models;

namespace Registration_løsning.Models
{
    public class Order
    {
        public int Id { get; set; } 
        public Kunde Kunde { get; set; }
        public Film Film { get; set; }
       

    }


}

Registration_løsning/Controllers/BestillingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DAL;
using Model;


namespace Registration_løsning.Controllers
{
    public class BestillingController : Controller
    {
        // init database
        DB db;

        public BestillingController()
        {
            db = new DB();

        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }


        //public ActionResult Bestilling()
        //{

        //    return View();

        //}



        //[HttpPost]
        //public ActionResult Bestilling(Order innOrder)
        //{

        //    Order order = new Order();
        //    order.Film = innOrder.Film;
        //    order.Kunde = innOrder.Kunde;


        //    db.Order.Add(order);
        //    db.SaveChanges();



        //    return RedirectToAction("Order");

        //}



        public ActionResult Order()
        {
            List<Model.Order> alleOrder = db.Order.ToList();

            return View(alleOrder);
        }



        /*--------------------------------------------------------------------------*/
        public ActionResult FilmListe()
        {
            List<Model.Film> alleFilmer = db.Film.ToList();

            return View(alleFilmer);
        }

        public ActionResult Leggfilm()
        {
            return View();
        }

        public ActionResult SlettFilm(int id)
        {
            var film = db.Film.SingleOrDefault(b => b.Id == id);
            db.Film.Remove(film);
            db.SaveChanges();
            return RedirectToAction("FilmListe");
        }

        [HttpPost]
        public ActionResult Leggfilm(Film innFilm)
        {
            // Sjekk hvis kunden eksisterer 

            var dbFilm = db.Film.SingleOrDefault(k => k.Title == innFilm.Title);

            if (dbFilm == null)
            {
                Film film = new Film();
                film.Title = innFilm.Title;
                film.Pris = innFilm.Pris;
                film.Catrgory = innFilm.Catrgory;
                film.Discription = innFilm.Discription;
                film.Image = innFilm.Image;

                db.Film.Add(film);
                db.SaveChanges();

                return RedirectToAction("FilmListe");
            }

            return RedirectToAction("FilmListe");

        }


        public ActionResult Handelkurve()
        {
            List<Film> filmer = new List<Film>();
            if (Session["handelKurv"] != null)
            {
                filmer = (List<Film>)Session["handelKurv"];
            }

            return View(filmer);
        }


        public ActionResult Bestill(int id)
        {
            var nyFilm = db.Film.SingleOrDefault(f => f.Id == id);

            if (Session["handelKurv"] == null)
            {
                List<Film> filmer = new List<Film>();
                filmer.Add(nyFilm);
                Session["handelKurv"] = filmer;
                Session["Antall"] = filmer.Count;

            }
            else
            {
                List<Film> filmer = (List<Film>)Session["handelKurv"];
                filmer.Add(nyFilm);
                Session["handelKurv"] = filmer;
                Session["Antall"] = filmer.Count;
            }


            return RedirectToAction("Handelkurve", nyFilm);


        }


        public ActionResult Betal()
        {
            return View();
        }




        public ActionResult SlettFilmFraHandelkurve(int id)
        {
            var filmer = (List<Film>)Session["handelKurv"];
            foreach (var film in filmer.ToList())
            {
                if (film.Id == id)
                {

                    filmer.Remove(film);
                }
            }
            Session["handelKurv"] = filmer;


            return RedirectToAction("HandelKurve");


        }
        //Legger kjøpt film til ordre og ordrelinje tabellen. 
        public ActionResult LeggFilmtilOrder()
        {
            var filmer = (List<Film>)Session["handelKurv"];
            // henter kunden
            int id = Convert.ToInt32(Session["UserID"]);
            var kunde = db.Kunder.Find(id);

            // Lager ordre
            var order = new Order();


            List<OrderLinje> ordrelinjer = new List<OrderLinje>();
            // Lager ordrelinjer 
            foreach (var film in filmer)
            {
                var ordrelinje = new OrderLinje();
                ordrelinje.FilmId = film.Id;
                ordrelinje.OrderId = order.Id;
                ordrelinjer.Add(ordrelinje);
            }

            // Lenker ordre og ordrelinje 

            order.OrdreLinjer = ordrelinjer;
            order.dbKundeId = kunde.id;

            // Lenker kunde og ordre

            // Her sjekkes hvis kunde har ordre fra f?r 
            if (kunde.Ordrer != null)
            {
                kunde.Ordrer.Add(order);
            }
            else
            {
                // lager ny liste 
                List<Order> ordreListe = new List<Order>();
                ordreListe.Add(order);
                kunde.Ordrer = ordreListe;
            }


            // lagre endringen
            db.SaveChanges();


            Session["handelKurv"] = null;


            return RedirectToAction("Index", "Home");
        }

    }
}

Registration_løsning/Views/Bestilling/Bestill.cshtml
@model IEnumerable<Registration_løsning.Models.Film>

@{
    ViewBag.Title = "Bestill";
}

<h2>Bestill</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pris)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Catrgory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pris)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Catrgory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Registration_løsning/Views/Bestilling/Betal.cshtml
@model Model.Film

@{
    ViewBag.Title = "Betal";
}


<div class="container py-3">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 mx-auto">
            <div id="pay-invoice" class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h2 class="text-center">Betal</h2>
                    </div>
                    <hr>
                    <form>
                        <input type="hidden" id="x_first_name" name="x_first_name" value="">
                        <input type="hidden" id="x_last_name" name="x_last_name" value="">
                        <input type="hidden" id="x_card_num" name="x_card_num" value="">
                        <input type="hidden" id="x_exp_date" name="x_exp_date" value="">
                        <div class="form-group text-center">
                            <ul class="list-inline">
                                <li class="list-inline-item"><img src="http://bootstrap-ecommerce.com/main/images/icons/pay-visa.png"><i class="text-muted fa fa-cc-visa fa-2x"></i></li>
                                <li class="list-inline-item"> <img src="http://bootstrap-ecommerce.com/main/images/icons/pay-mastercard.png"><i class="fa fa-cc-mastercard fa-2x"></i></li>
                                <li class="list-inline-item"><img src="http://bootstrap-ecommerce.com/main/images/icons/pay-american-ex.png"><i class="fa fa-cc-amex fa-2x"></i>
                                </li>
                                <li class="list-inline-item"><i class="fa fa-cc-discover fa-2x"></i></li>
                            </ul>
                        </div>                       

                        <div class>
                            <label for="cc-name">Navn på kort eier</label>
                            <input id="cc-name" name="cc-name" pattern="[A-Z a-z\s]{1,35}" required type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter the name on card" placeholder="Navn på kort" autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error">
                            
                        </div>
                        <div>
                            <label for="cc-number">Kortnummer</label>
                            <input id="cc-number"  name="cc-number" pattern="[0-9]{16}"  required type="text" class="form-control cc-number identified visa" value="" data-val="true" data-val-required="Please enter the card number" data-val-cc-number="Please enter a valid card number" placeholder="Kortnummer" autocomplete="cc-number">
                           
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="cc-exp">Utløpsdato</label>
                                    <input id="cc-exp"  name="cc-exp" pattern="(([0-9]{2})/([0-9]{2}))"  required type="text" class="form-control cc-exp" value="" data-val="true" data-val-required="Please enter the card expiration" data-val-cc-exp="Please enter a valid month and year" placeholder="MM / YY" autocomplete="cc-exp">
                                   
                                </div>
                            </div>
                            <div class="col-6">
                                <label for="x_card_code">Sikkerhetskode/CCV</label>
                                <div class="input-group">
                                    <input id="x_card_code"  name="x_card_code" pattern="[0-9]{3}"  required type="tel" class="form-control cc-cvc" value="" data-val="true" data-val-required="Please enter the security code" data-val-cc-cvc="Please enter a valid security code" placeholder="Sikkeretskode"  autocomplete="off">
                                    <div class="input-group-addon">
                                       
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            
                                <a class="btn btn-primary btn-lg" href="/bestilling/LeggFilmtilOrder" style="background-color:red">Betal</a>
                        
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Registration_løsning/Views/Bestilling/FilmListe.cshtml
@model IEnumerable<Model.Film>

@{
    ViewBag.Title = "FilmListe";
}

<h2>FilmListe</h2>

<p>
    @Html.ActionLink("Create New", "Leggfilm")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pris)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Catrgory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discription)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pris)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Catrgory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discription)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "SlettFilm", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Registration_løsning/Views/Bestilling/Handelkurve.cshtml
@model IEnumerable<Model.Film>

@{
    ViewBag.Title = "Handelkurve";
}


<h2 class="text-light">Handelkurve</h2>


<table class="table text-light">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pris)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Catrgory)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pris)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Catrgory)
            </td>
            <td>
                <a class="btn btn-primary btn-lg" href="/bestilling/SlettFilmFraHandelkurve?id=@item.Id" style="background-color:red">Slett</a>
            </td>


        </tr>
    }

</table>


<dd>
    @if (Session["UserId"] == null)
    {

        <a class="btn btn-primary btn-lg" href="/Home/Index" style="background-color:dodgerblue">forsett å handle</a>

        <h4 class="text-light">Du må være innlogget for å gjennomføre bataling</h4>

    }

    @if (Session["UserId"] != null)
    {

        <a class="btn btn-primary btn-lg" href="/Home/Index" style="background-color:dodgerblue">forsett å handle</a>

        <a class="btn btn-primary btn-lg" href="/bestilling/Betal?id=@Model*/" style="background-color:dodgerblue">Betal</a>
    }

</dd>

Registration_løsning/Views/Bestilling/Leggfilm.cshtml
@model Model.Film

@{
    ViewBag.Title = "Leggfilm";
}

<h2>Leggfilm</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Film</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pris, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pris, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pris, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Catrgory, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Catrgory, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Catrgory, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Discription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Discription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Discription, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Liggfilm" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "FilmListe")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Registration_løsning/Views/Bestilling/Order.cshtml
@model IEnumerable<Model.Order>

@{
    ViewBag.Title = "Order";
}

<h2>Order</h2>

<p>
    @Html.ActionLink("Create New", "Bestilling")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Kunde.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Film.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Film.Pris)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Film.Catrgory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Film.Discription)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Kunde.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Film.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Film.Pris)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Film.Catrgory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Film.Discription)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>